version: '3'

services:
    snmp_collector:
        build: .
        image: snmp_collector:2.0.0
        network_mode: "host"
        container_name: snmp_collector
        restart: unless-stopped
        ports:
          - 6669:6669
        expose:
          - 9001

        volumes:
          - /etc/localtime:/etc/localtime:ro
#          - ./config/config.json:/app/config/config.json:rw
          - ./config:/app/config

        logging:
          driver: "json-file"
          options:
            max-size: "50m"
