version: '3'

services:
    snmp_collector:
        build: .
        image: snmp_collector:2.0.0
        network_mode: "host"
        container_name: snmp_collector
        restart: unless-stopped

        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./config:/app/config

        logging:
          driver: "json-file"
          options:
            max-size: "20m"
