version: '3'

services:
    snmp_collector:
        build: .
        image: snmp_collector:2.0.0
        network_mode: "host"
        container_name: snmp_collector
        restart: unless-stopped
        ports:
          - 6669:6669
#          - 9898:9898
#        expose:
#          - 9001
#          - 9898

        volumes:
          - /etc/localtime:/etc/localtime:ro
#          - ./config/config.json:/app/config/config.json:rw
          - ./config:/app/config

        logging:
          driver: "json-file"
          options:
            max-size: "20m"

        environment:
          - SENTRY_DSN=http://78bb380df55444c584d010e0edfc3859@192.168.1.136/5
